## Introduction

K-Nearest Neighbors (KNN) is a simple and powerful machine learning algorithm used for classification, regression, and recommendation systems. It works by finding the most similar data points based on distance metrics.

In real life, KNN is used in recommendation systems like Netflix, Amazon, and Spotify to suggest items based on user preferences.

## What is KNN?

KNN (K-Nearest Neighbors) is a supervised learning algorithm that classifies or predicts data based on the 'K' closest neighbors.

### Key Points:
- It stores all data points
- It calculates distance between points
- It finds the nearest neighbors
- It makes predictions based on similarity

### Common Distance Metrics:
- Euclidean Distance
- Cosine Similarity (used in recommendation systems)

## Netflix-like Recommendation using KNN

Netflix uses recommendation systems to suggest movies or shows based on user behavior.

### Two main approaches:

### 1. User-Based KNN
- Finds users similar to you
- Recommends movies liked by those users

### 2. Item-Based KNN
- Finds movies similar to what you watched
- Recommends similar movies

### Example:

| User   | Movie A | Movie B | Movie C |
|--------|--------|--------|--------|
| User1  | 5      | 3      | 0      |
| User2  | 4      | 2      | 1      |
| User3  | 1      | 5      | 4      |

If a new user likes Movie A and Movie B, KNN finds similar users and recommends Movie C.

In [2]:
import numpy as np
from sklearn.neighbors import NearestNeighbors

In [3]:
# Sample user-movie rating data
# Rows = Users, Columns = Movies

data = np.array([
    [5, 3, 0],   # User1
    [4, 2, 1],   # User2
    [1, 5, 4],   # User3
    [0, 0, 5]    # User4
])

print("Dataset:\n", data)

Dataset:
 [[5 3 0]
 [4 2 1]
 [1 5 4]
 [0 0 5]]


In [4]:
# Create KNN model using cosine similarity
model = NearestNeighbors(metric='cosine', algorithm='brute')

# Fit the model
model.fit(data)

NearestNeighbors(algorithm='brute', metric='cosine')

In [5]:
# New user (likes Movie A & B)
new_user = np.array([[5, 3, 0]])

print("New User:", new_user)

New User: [[5 3 0]]


In [6]:
# Find 2 nearest neighbors
distances, indices = model.kneighbors(new_user, n_neighbors=2)

print("Nearest Users Index:", indices)
print("Distances:", distances)

Nearest Users Index: [[0 1]]
Distances: [[2.22044605e-16 2.69744549e-02]]


In [7]:
# Show ratings of similar users
for i in indices[0]:
    print(f"User {i+1} ratings:", data[i])

User 1 ratings: [5 3 0]
User 2 ratings: [4 2 1]


## Conclusion

KNN is a simple and effective algorithm for recommendation systems. It works by identifying similar users or items based on distance metrics like cosine similarity.

In this assignment, we implemented a basic KNN model to simulate a Netflix-like recommendation system. Based on user similarity, we can recommend new movies that the user has not watched yet.